# Generated by Django 3.2.9 on 2021-11-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_asso',
            name='class_associated',
            field=models.CharField(default='ss', max_length=10, unique=True),
        ),
    ]
